# Generated by Django 5.0.2 on 2024-02-15 23:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_name", models.CharField(max_length=50)),
                (
                    "doctor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("doctor_phone", models.IntegerField()),
                ("doctor_image", models.ImageField(upload_to="img/doctors")),
                ("doctor_desc", models.CharField(max_length=50)),
                (
                    "address",
                    models.CharField(
                        default="HealthPlus, Rohini-22, New Delhi", max_length=100
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("available", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("visitor_name", models.CharField(max_length=50)),
                (
                    "visitor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("visitor_phone", models.IntegerField()),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2024, 2, 16, 2, 19, 55, 252716)
                    ),
                ),
                (
                    "time_in",
                    models.TimeField(
                        default=datetime.datetime(2024, 2, 16, 2, 19, 55, 252748)
                    ),
                ),
                ("time_out", models.TimeField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="meetingSchedule.doctor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="current_meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_meeting",
                to="meetingSchedule.meeting",
            ),
        ),
    ]
