# Generated by Django 5.0.2 on 2024-02-16 00:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetingSchedule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="current_meeting",
        ),
        migrations.AddField(
            model_name="doctor",
            name="current_meeting_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="doctor_image",
            field=models.ImageField(blank=True, null=True, upload_to="static/media"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="doctor_phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2024, 2, 16, 3, 33, 39, 795982)
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="visitor_phone",
            field=models.CharField(max_length=15),
        ),
    ]
